# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23959cbcdd2533f6f43729c73925859170ed3797672ddb2d6adbea1964df1f6cf78ec5d1f15ed26e1822081443105cece0815fda33afd2c19eda50961ef325e7
  stripe_publishable_key: pk_test_idVcTQhmG9oYcwz9iX07soWj
  stripe_secret_key: sk_test_d5Yy0gi4fsMbERNeU9lWJb3V

staging:
  secret_key_base: 23959cbcdd2533f6f43729c73925859170ed3797672ddb2d6adbea1964df1f6cf78ec5d1f15ed26e1822081443105cece0815fda33afd2c19eda50961ef325e7
  stripe_publishable_key: pk_test_idVcTQhmG9oYcwz9iX07soWj
  stripe_secret_key: sk_test_d5Yy0gi4fsMbERNeU9lWJb3V

test:
  secret_key_base: 9ec50d6e3c32503dc858a1891074f8fd62c34652613c635d4adb297d7831c71e253e7ae76f915e8fed4063c457d215ef4aad78c6aa9306e93c0a8c4c8065e644
  stripe_publishable_key: pk_test_idVcTQhmG9oYcwz9iX07soWj
  stripe_secret_key: sk_test_d5Yy0gi4fsMbERNeU9lWJb3V

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISH_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
